### ISSUE TITLE
App crashes in iOS 7

### ISSUE THREAD

**Issue by secobarbital** [ben-ng/phonegap-air#7]
The app crashes on startup in iOS 7 because of the use of ```containsString:```. We managed to get around this by [retrofitting containsString in iOS 7][1] but you might want to reconsider the use of this new method instead.

[1]: http://petersteinberger.com/blog/2014/retrofitting-containsstring-on-ios-7/

**Comment by ben-ng** [comment]
Thanks for the heads up, i've been only supporting ios8 so i haven't run into this. I will fix this soon though.. a lot of our customers still use ios7 so if this is the only issue holding it up, might as well fix it and support ios7 too.

**Comment by ben-ng** [comment]
Resolved in a2f63fb6bfdfc4a60ce64de42ded895e46b0db28
