### ISSUE TITLE
the content  src in config.xml problem

### ISSUE THREAD

**Issue by wliment** [ben-ng/phonegap-air#9]
my  phonegap code work  in chrome browser and android  and orginal phonegap framwork,

but now  it has some problem with phonegap-air
if i set the content start page  with a subdir , example: pages/login.html)    
 content src="pages/login.html" 
 
the content of pages/login.html will not loaded  excpet hte login.html ;

 src="images/login_logo.png"  not  load  in pages/login.html 
 the images dir  is a subdir in pages  dir. 

![image](https://cloud.githubusercontent.com/assets/600490/6935403/2f055e78-d877-11e4-9ef6-355eb0950497.png)

if i change this to  src="pages/images/login_logo.png"  the  login_logo.png will show in pages/login.html page.

**Comment by ben-ng** [comment]
Yes, all paths are made relative to the app root because the index src is loaded as if it was at the app root.

**Comment by wliment** [comment]
@ben-ng   i sovle this issue ,
i add a file in root named index.html  and redirect it to /pages/login.html, so now all file loaded correct

**Comment by ben-ng** [comment]
Thanks for the follow up. Running web code on phonegap doesn't follow the same rules that you expect on a server because of the filesystem.
